config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('users/', include('users.urls', namespace='users'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.forms import CustomPasswordResetForm
from users.views import RegisterUser, email_verification, PasswordResetView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),  # 11
    path('password-reset/', PasswordResetView.as_view(form_class=CustomPasswordResetForm), name="password_reset",),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'null': True, 'blank': True}


# Create your models here.
class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='email')
    phone = models.CharField(max_length=35, **NULLABLE, verbose_name='phone')
    avatar = models.ImageField(upload_to='user/', **NULLABLE, verbose_name='avatar')
    country = models.CharField(max_length=100, **NULLABLE, verbose_name='country')
    token = models.CharField(max_length=100, **NULLABLE, verbose_name='token')  # 4

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return f'{self.email}'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class CustomPasswordResetForm(forms.Form):
    email = forms.EmailField(
        label="email", max_length=254, help_text="Введите email для отправки"
    )

users/views.py
import secrets  # 5

from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, FormView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm
from users.models import User


class RegisterUser(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):  # 2
        user = form.save()
        user.is_active = False  # 3
        token = secrets.token_hex(16)  # 6
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'  # 7
        send_mail(
            subject='Подтверждение регистрации',
            message=f'Здравствуйте! Для подтверждения регистрации перейдите по ссылке: {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )  # 8
        return super().form_valid(form)  # 9


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))  # 10


class PasswordResetView(FormView):
    template_name = "password_reset.html"
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        email = form.cleaned_data["email"]

        user = User.objects.get(email=email)

        new_password = User.objects.make_random_password()

        user.set_password(new_password)
        user.save()

        send_mail(
            subject="Новый пароль",
            message=f"Ваш новый пароль: {new_password}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[email],
        )

        return super().form_valid(form)

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Log in
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Login
                    </button>
                    <a href="{% url 'users:password_reset' %}" class="btn btn-link btn-sm">
                        Восстановить пароль
                    </a>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Registration
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Registration
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}