catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ContactDetailView, HomeListView, GenresListView, GameDetailView, GameCreateView, \
    GameUpdateView, GameDeleteView, BlogListView, BlogDetailView, BlogUpdateView, BlogCreateView, BlogDeleteView

app_name = CatalogConfig.name

urlpatterns = [
                  path('', HomeListView.as_view(), name='games_list'),
                  path('contacts/', ContactDetailView.as_view(), name='contacts'),
                  path('genres_list/', GenresListView.as_view(), name='genres'),
                  path('game_detail/<slug:slug>/', cache_page(60)(GameDetailView.as_view()), name='game_detail'),
                  path('create/', GameCreateView.as_view(), name='game_create'),
                  path('update/<slug:slug>/', GameUpdateView.as_view(), name='game_update'),
                  path('delete/<slug:slug>/', GameDeleteView.as_view(), name='game_delete'),

                  path('blog/', BlogListView.as_view(), name='blog_list'),
                  path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
                  path('blog/detail/<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
                  path('blog/update/<slug:slug>/', BlogUpdateView.as_view(), name='blog_update'),
                  path('blog/delete/<slug:slug>/', BlogDeleteView.as_view(), name='blog_delete'),
              ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('users/', include('users.urls', namespace='users'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.forms import CustomPasswordResetForm
from users.views import RegisterUser, email_verification, PasswordResetView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),  # 11
    path('password-reset/', PasswordResetView.as_view(form_class=CustomPasswordResetForm), name="password_reset",),
]

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='наименование категории')
    description = models.TextField(**NULLABLE, verbose_name='описание')
    photo = models.ImageField(upload_to='catalog/', **NULLABLE, verbose_name='фото')
    slug = models.CharField(max_length=150, **NULLABLE, verbose_name='URL')

    def __str__(self):
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    product_name = models.CharField(max_length=250, verbose_name='название продукта', unique=True, **NULLABLE)
    description = models.TextField(verbose_name='описание')
    photo = models.ImageField(upload_to='catalog/', **NULLABLE, verbose_name='фото')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price_of_product = models.IntegerField(verbose_name='цена за товар')
    created_at = models.DateField(auto_now_add=True, verbose_name='дата создания')
    updated_at = models.DateField(auto_now=True, verbose_name='дата последнего изменения')
    slug = models.CharField(max_length=150, **NULLABLE, verbose_name='URL')
    owner = models.ForeignKey(User, verbose_name="Владелец", help_text="Укажите владельца", **NULLABLE,
                              on_delete=models.SET_NULL)

    is_published = models.BooleanField(default=False, **NULLABLE, verbose_name='is_published')

    def __str__(self):
        return (f'{self.product_name} {self.photo}'
                f'{self.description} {self.price_of_product} Руб.'
                f'{self.created_at} {self.updated_at}')

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        permissions = [
            ('can_edit_is_published', 'Can edit is published'),
            ('can_edit_description', 'Can edit description'),
            ('can_edit_category', 'Can edit category')
        ]


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='название статьи')
    slug = models.CharField(max_length=150, **NULLABLE, verbose_name='URL')
    description = models.TextField(verbose_name='описание')
    photo = models.ImageField(upload_to='blog/', **NULLABLE, verbose_name='фото')
    created_at = models.DateField(auto_now_add=True, verbose_name='дата создания')
    sign_of_publication = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.PositiveIntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.title} {self.description}'

    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, **NULLABLE, verbose_name='продукт')
    version = models.PositiveIntegerField(verbose_name='версия')
    title = models.CharField(max_length=150, verbose_name='название версии')
    is_active = models.BooleanField(default=True, verbose_name='признак активной версии')

    def __str__(self):
        return f'{self.product}.'

    class Meta:
        verbose_name = 'версия продукта'
        verbose_name_plural = 'версии продуктов'

catalog/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from catalog.models import Product, Version

FORBIDDEN_WORDS = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class GameForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        fields = (
            'product_name', 'description', 'photo', 'category', 'price_of_product', 'slug', 'owner', 'is_published')

    def clean_product_name(self):
        product_name = self.cleaned_data.get('product_name')
        if product_name in FORBIDDEN_WORDS:
            raise ValidationError('Нельзя использовать запрещенные слова')
        return product_name

    def clean_description(self):
        description = self.cleaned_data.get('description')
        if description in FORBIDDEN_WORDS:
            raise ValidationError('Нельзя использовать запрещенные слова')
        return description


class GameModeratorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        fields = ('is_published', 'description', 'category')


class VersionProductForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Version
        fields = ('product', 'version', 'title', 'is_active',)

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from catalog.forms import GameForm, VersionProductForm, GameModeratorForm
from catalog.models import Product, Category, Blog, Version
from catalog.services import get_genres_from_cache


class HomeListView(ListView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        for product in context_data['object_list']:
            product.active_version = product.version_set.filter(is_active=True).last()
        return context_data


class ContactDetailView(DetailView):
    model = Product


class GameDetailView(DetailView):
    model = Product


class GenresListView(ListView):
    model = Category

    def get_queryset(self, *args, **kwargs):  # возвращаем кэш категорий
        return get_genres_from_cache()


class GameCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = GameForm
    success_url = reverse_lazy('catalog:games_list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.product_name)
            new_blog.save()

        product = form.save()
        user = self.request.user

        product.owner = user
        product.save()

        return super().form_valid(form)


class GameUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = GameForm
    success_url = reverse_lazy('catalog:games_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        SubjectFormset = inlineformset_factory(
            Product, Version, form=VersionProductForm, extra=1)
        if self.request.method == "POST":
            context_data["formset"] = SubjectFormset(self.request.POST, instance=self.object)
        else:
            context_data["formset"] = SubjectFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.product_name)
            new_blog.save()

        return super().form_valid(form)

    def form_valid_formset(self, form):
        formset = self.get_context_data()["formset"]
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return GameForm
        if user.has_perm('catalog.can_edit_is_published') and user.has_perm(
                'catalog.can_edit_description') and user.has_perm('catalog.can_edit_category'):
            return GameModeratorForm
        raise PermissionDenied


class GameDeleteView(DeleteView, LoginRequiredMixin):
    model = Product
    success_url = reverse_lazy('catalog:games_list')


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(sign_of_publication=True)
        return queryset


class BlogCreateView(CreateView, LoginRequiredMixin):
    model = Blog
    fields = ['title', 'description', 'photo']
    success_url = reverse_lazy('catalog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class BlogDetailView(DetailView, LoginRequiredMixin):
    model = Blog

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.views_count += 1
        obj.save()
        return obj


class BlogUpdateView(UpdateView, LoginRequiredMixin):
    model = Blog
    slug_field = 'slug'
    fields = ['title', 'description', 'photo']

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:blog_detail', kwargs={'slug': self.object.slug})


class BlogDeleteView(DeleteView, LoginRequiredMixin):
    model = Blog
    success_url = reverse_lazy('catalog:blog_list')

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>GameStore.ru</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">


    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
          z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
    </style>


</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<header data-bs-theme="dark">
    {% include "catalog/includes/inc_menu.html" %}
</header>

<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-1">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">GameStore</h1>
            </div>
        </div>
    </section>

    {% block content %}

    {% endblock %}

</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
        </p>
        <p class="mb-1">2024 -{% now 'Y' %}</p>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <p class="card-text">Действительно хотите удалить "{{ object.title }}" ?</p>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success">
                            Удалить
                        </button>
                        <a href="{% url 'catalog:blog_list' %}"
                           class="btn btn-sm btn-outline-secondary">Отменить</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load media %}
{% block content %}
<div class="col-6">
    <div class="card shadow-sm">
        <img src="{{ object.photo | media }}">
        <div class="card-body">
            <p class="card-text">Название блога: "{{ object.title }}"</p>
            <p class="card-text">Описание: {{ object.description }}</p>
            <div class="d-flex justify-content-between align-items-center">
            </div>
            <div class="card-footer">
                Просмотры: {{ object.views_count }}
            </div>
            <div class="btn-group">
                <a href="{% url 'catalog:blog_list' %}"
                   class="btn btn-sm btn-outline-secondary">На главную</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="btn-group">
    <a href="{% url 'catalog:blog_create' %}"
       class="btn btn-sm btn-outline-secondary">Создать</a>
</div>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ object.photo}}">
                    <div class="card-body">
                        <p class="card-text">{{ object.title }}</p>
                        <p class="card-text">{{ object.description }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">

                                <a href="{% url 'catalog:blog_detail' object.slug %}"
                                   class="btn btn-sm btn-outline-secondary">Подробнее</a>
                                {% if user.is_authenticated %}
                                <a href="{% url 'catalog:blog_update' object.slug %}"
                                   class="btn btn-sm btn-outline-secondary">Изменить</a>
                                <a href="{% url 'catalog:blog_delete' object.slug %}"
                                   class="btn btn-sm btn-outline-secondary">Удалить</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% load media %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ object.photo | media }}">
                    <div class="card-body">
                        <p class="card-text">{{ object.name }}</p>
                        <p class="card-text">{{ object.description}}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <p class="card-text">Действительно хотите удалить "{{ object.product_name }}" ?</p>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success">
                            Удалить
                        </button>
                        <a href="{% url 'catalog:games_list' %}"
                           class="btn btn-sm btn-outline-secondary">Отменить</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load media %}
{% block content %}
<div class="col">
    <div class="card shadow-sm">
        <img src="{{ object.photo | media }}">
        <div class="card-body">
            <p class="card-text">Название игры: {{ object.product_name }}</p>
            <p class="card-text">Цена: {{ object.price_of_product }} Руб.</p>
            <p class="card-text">Жанр: {{ object.category }}</p>
            <p class="card-text">Описание: {{ object.description }}</p>
            <p class="card-text">Автор: {{ object.owner }}</p>
            <div class="d-flex justify-content-between align-items-center">
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load filter %}
{% load media %}
{% block content %}

{% if user.is_authenticated %}
<div class="btn-group">
    <a href="{% url 'catalog:game_create' %}"
       class="btn btn-sm btn-outline-secondary">Добавить новую игру</a>
</div>
{% endif %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ object.photo | media }}">
                    <div class="card-body">
                        <p class="card-text">{{ object.product_name }}</p>
                        <p class="card-text">{{ object.price_of_product }} Руб.</p>
                        <p class="card-text">{{ object.description | slice }}</p>
                        <div class="d-flex justify-content-between align-items-center">

                            <div class="btn-group">
                                {% if perms.object.can_edit_is_published and perms.object.can_edit_description and perms.object.can_edit_category or user == object.owner %}
                                <a href="{% url 'catalog:game_update' object.slug %}"
                                   class="btn btn-sm btn-outline-secondary">Изменить</a>
                                {% endif %}
                                <a href="{% url 'catalog:game_detail' object.slug %}"
                                   class="btn btn-sm btn-outline-secondary">Подробнее</a>
                                <a href="{% url 'catalog:game_delete' object.slug %}"
                                   class="btn btn-sm btn-outline-secondary">Удалить</a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}